---
- name: "Ensure the '{{ docker_base_path }}' directory exists"
  ansible.builtin.file:
    path: "{{ docker_base_path }}"
    state: "directory"
    mode: "0755" # Allow user, group, and others to access the directory.

- name: "Copying the application's file to the target at: '{{ app_path }}'"
  ansible.builtin.copy:
    src: "docker/"
    dest: "{{ app_path }}"
    mode: "preserve"

- name: "Copying the application's SSL Certificate to the target"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ certificates_dest_path }}"
    mode: "preserve"
  loop: "{{ certificates }}"

- name: "Creating external Docker network for reverse proxy"
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver }}"
    state: "{{ item.state | default('present', true) }}"
  loop: "{{ networks }}"

- name: "Creating and starting services (docker-compose up)"
  community.docker.docker_compose_v2:
    project_name: "loadbalancer"
    project_src: "{{ app_path }}"
    # This will apply changes without restarting the containers unnecessarily.
    state: "present"
