global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: "ERROR"
# filePath: "/etc/traefik/logs/traefik.log"

# accessLog:
#   filePath: "/etc/traefik/logs/access.log"

api:
  dashboard: true

providers:
  file:
    directory: "/etc/traefik/sites"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true

  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: false
  rootCAs:
    - "/etc/traefik/certificates/certificate.authority.crt"

# ping:
#   entryPoint: "websecure"

# metrics:
#   prometheus:
#     buckets:
#       - 0.1
#       - 0.3
#       - 1.2
#       - 5.0
