http:
  routers:
    secure-loadbalancer:
      entryPoints:
        - "websecure"
      service: "api@internal"
      rule: "Host(`loadbalancer.homelab`, `loadbalancer-01.homelab`, `loadbalancer-02.homelab`)"
      middlewares:
        - "headers-rate-limit-loadbalancer"
        - "headers-inFlightReq"
        - "headers-security"
        # - "headers-compress"
      tls:
        options: "tls-loadbalancer"
