http:
  middlewares:
    headers-compress:
      compress: {}

    headers-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    headers-inFlightReq:
      inFlightReq:
        amount: 10

    headers-default:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        frameDeny: true
        browserXssFilter: true

    headers-security:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        accessControlMaxAge: 100
        addVaryheader: true
        referrerPolicy: "origin-when-cross-origin"
