---
- name: "Preparing the virtual machine with the initial settings"
  ansible.builtin.import_playbook: "setup_vm.yml"

- name: "Setting up the Application"
  ansible.builtin.import_playbook: "setup_app.yml"
