---
- name: "Updating packages"
  ansible.builtin.import_tasks: "update.yml"

- name: "Checking if a reboot is required"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/reboot-if-required.yml"
