---
# The name of the root user used in VM.
ansible_user: "usr_ansible"

# The id of the password saved in the secret manager.
root_password_id: "{{ password_id }}"

# The password of the root user used in VM.
ansible_password: "{{ lookup('pipe', 'secret-tool lookup password ' + root_password_id) }}"

docker_path: "/opt/docker"
certificates_dest_path: "{{ docker_path }}/certificates"

certificates_src_path: "/opt/certificates"
cert_root_ca_src_path: "{{ certificates_src_path }}/certificate.authority"
cert_loadbalancer_src_path: "{{ certificates_src_path }}/loadbalancer.lan.homelab"
cert_kvm_src_path: "{{ certificates_src_path }}/kvm.lan.homelab"

certificates:
  - "{{ cert_root_ca_src_path }}/certificate.authority.crt"
  - "{{ cert_loadbalancer_src_path }}/loadbalancer.lan.homelab.crt"
  - "{{ cert_loadbalancer_src_path }}/loadbalancer.lan.homelab.key"
  - "{{ cert_kvm_src_path }}/kvm.lan.homelab.crt"
  - "{{ cert_kvm_src_path }}/kvm.lan.homelab.key"
